name: CI Workflow

on:
  workflow_dispatch:
    inputs:
      RUN_SELENIUM_JAVA:
        type: boolean
        default: false
      RUN_SELENIUM_POP:
        type: boolean
        default: false
      RUN_SELENIUM_JS:
        type: boolean
        default: false
      RUN_PLAYWRIGHT_JAVA:
        type: boolean
        default: false
      RUN_PLAYWRIGHT_JS:
        type: boolean
        default: false
      RUN_CYPRESS_JS:
        type: boolean
        default: false
      NUMBER_OF_RUNS:
        type: string
        default: '10'

jobs:
  playwright:
    runs-on: self-hosted
    if: inputs.RUN_PLAYWRIGHT_JAVA || inputs.RUN_PLAYWRIGHT_JS
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Playwright Java
        if: inputs.RUN_PLAYWRIGHT_JAVA
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --privileged --network host maven:3.9.8 bash -c "
          cd playwright/java &&
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args='install-deps' &&
          mvn test-compile &&
          for i in $(seq 1 ${inputs.NUMBER_OF_RUNS}); do
            mvn clean test || true
          done &&
          cp timings.csv playwright-java.csv &&
          exit 0"
          mv playwright/java/playwright-java.csv .

      - name: Run Playwright JavaScript
        if: inputs.RUN_PLAYWRIGHT_JS
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --privileged --network host node:20.15.1-bookworm bash -c "
          cd playwright/js &&
          npm ci &&
          npx playwright install &&
          npx playwright install-deps &&
          for i in $(seq 1 ${inputs.NUMBER_OF_RUNS}); do
            npm run test || true
          done &&
          cp timings.csv playwright-js.csv &&
          exit 0"
          mv playwright/js/playwright-js.csv .
