name: CI Workflow

on:
  workflow_dispatch:
    inputs:
      RUN_SELENIUM_JAVA:
        type: boolean
        default: false
      RUN_SELENIUM_POP:
        type: boolean
        default: false
      RUN_SELENIUM_JS:
        type: boolean
        default: false
      RUN_PLAYWRIGHT_JAVA:
        type: boolean
        default: false
      RUN_PLAYWRIGHT_JS:
        type: boolean
        default: false
      RUN_CYPRESS_JS:
        type: boolean
        default: false
      NUMBER_OF_RUNS:
        type: string
        default: '2'

jobs:
  playwright:
    runs-on: self-hosted
    if: inputs.RUN_PLAYWRIGHT_JAVA || inputs.RUN_PLAYWRIGHT_JS
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    
    steps:
      - name: Install system dependencies (if needed)
        run: |
          apt-get update && apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Playwright Java
        if: inputs.RUN_PLAYWRIGHT_JAVA
        run: |
          cd playwright/js
          npm ci
          npx playwright install
          npx playwright install-deps
          npm run test
          
      - name: Debug timings.csv
        run: |
          ls -la
          if [ -f timings.csv ]; then
          echo "timings.csv exists."
          else
          echo "timings.csv not found."
          fi
          
      - name: Copy timings.csv to playwright-java.csv
        run: |
          if [ -f timings.csv ]; then
          cp timings.csv playwright-java.csv
          else
          echo "timings.csv not found. Skipping copy."
          fi

      - name: Upload playwright-java.csv as artifact
        if: inputs.RUN_PLAYWRIGHT_JAVA
        uses: actions/upload-artifact@v3
        with:
          name: playwright-java
          path: playwright-java.csv
          if-no-files-found: ignore

      - name: Run Playwright JavaScript
        if: inputs.RUN_PLAYWRIGHT_JS
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --privileged --network host node:20.15.1-bookworm bash -c "
          cd playwright/js &&
          npm ci &&
          npx playwright install &&
          npx playwright install-deps &&
          for i in $(seq 1 ${inputs.NUMBER_OF_RUNS}); do
            npm run test || true
          done &&
          cp timings.csv playwright-js.csv &&
          exit 0"
          mv playwright/js/playwright-js.csv .
